### ISSUE TITLE
making this work on Windows?

### ISSUE THREAD

**Issue by that-damn-chameleon** [domingguss/buzz#2]
I will be soon attempting to rewrite the HID handling so I could make these controllers work with Windows. 
I'm a newbie when it comes to low-level programming and I wanted to ask you if rewriting objective-C code from main.m should prove any difficult or there are things I should watch out while rewriting it to Windows-based machine?

**Comment by Rabshakeh** [comment]
Hi Ryuuto, How did you get on with the re-writing of the program ?
